var te=Object.create;var k=Object.defineProperty;var ne=Object.getOwnPropertyDescriptor;var ae=Object.getOwnPropertyNames;var se=Object.getPrototypeOf,ce=Object.prototype.hasOwnProperty;var h=(e,r)=>()=>(r||e((r={exports:{}}).exports,r),r.exports),ie=(e,r)=>{for(var t in r)k(e,t,{get:r[t],enumerable:!0})},b=(e,r,t,n)=>{if(r&&typeof r=="object"||typeof r=="function")for(let a of ae(r))!ce.call(e,a)&&a!==t&&k(e,a,{get:()=>r[a],enumerable:!(n=ne(r,a))||n.enumerable});return e},v=(e,r,t)=>(b(e,r,"default"),t&&b(t,r,"default")),P=(e,r,t)=>(t=e!=null?te(se(e)):{},b(r||!e||!e.__esModule?k(t,"default",{value:e,enumerable:!0}):t,e)),oe=e=>b(k({},"__esModule",{value:!0}),e);var x=h((_e,C)=>{var y=class{constructor(r,t){this.type=r,t&&(this.range=t)}},L=class extends y{constructor(r,t,n){super("PAIR",n),this.key=r,this.value=t}separator(r){if(Array.isArray(this.range)&&this.range.length>=3){let[t,n,a]=this.range;return r.slice(n,a)}return null}},O=class extends y{constructor(r,t){super("COMMENT",t),this.comment=r}},q=class extends y{constructor(r){super("EMPTY_LINE",r)}};C.exports={Node:y,Pair:L,Comment:O,EmptyLine:q}});var K=h((je,F)=>{var{Pair:I,Comment:ue,EmptyLine:le}=x(),pe=(e,r)=>{let t=e[r];return t==="#"||t==="!"},T=(e,r)=>{let t=e[r];return!t||t==="\r"||t===`
`},M=(e,r)=>{let t=e[r];for(;t==="	"||t==="\f"||t===" ";)r+=1,t=e[r];return r},ge=(e,r)=>{let t=e[r];for(;t&&t!=="\r"&&t!==`
`;)r+=1,t=e[r];return r},fe=(e,r)=>{let t=e[r];for(;t&&t!=="\r"&&t!==`
`&&t!=="	"&&t!=="\f"&&t!==" "&&t!==":"&&t!=="=";)t==="\\"?e[r+1]===`
`?r=M(e,r+2):r+=2:r+=1,t=e[r];return r},he=(e,r)=>{let t=e[r],n=!1;e:for(;t==="	"||t==="\f"||t===" "||t==="="||t===":"||t==="\\";){switch(t){case"\\":if(e[r+1]!==`
`)break e;r=M(e,r+2);break;case"=":case":":if(n)break e;n=!0;default:r+=1}t=e[r]}return r},ye=(e,r)=>{let t=e[r];for(;t&&t!=="\r"&&t!==`
`;)r+=t==="\\"?2:1,t=e[r],t===`
`&&e[r-1]==="\r"&&(r+=1,t=e[r]);return r},_=e=>e.replace(/\\(u[0-9a-fA-F]{4}|\r?\n[ \t\f]*|.)?/g,(r,t)=>{switch(t&&t[0]){case"f":return"\f";case"n":return`
`;case"r":return"\r";case"t":return"	";case"u":{let n=parseInt(t.substr(1),16);return isNaN(n)?t:String.fromCharCode(n)}case"\r":case`
`:case void 0:return"";default:return t}});function V(e,r){let t=[];for(let n=0;n<e.length&&(e[n]===`
`&&e[n-1]==="\r"&&(n+=1),!!e[n]);++n){let a=M(e,n);if(T(e,a)){t.push(r?new le([n,a]):""),n=a;continue}if(pe(e,a)){let l=ge(e,a),p=e.slice(a,l);t.push(r?new ue(p,[a,l]):p),n=l;continue}let s=fe(e,a),u=_(e.slice(a,s)),i=he(e,s);if(T(e,i)){t.push(r?new I(u,"",[a,s,i,i]):[u,""]),n=i;continue}let g=ye(e,i),o=_(e.slice(i,g));t.push(r?new I(u,o,[a,s,i,g]):[u,o]),n=g}return t}function j(e,r,t,n){if(!n){e[r]=t;return}let a=r.split(n),s=e;for(;a.length>=2;){let i=a.shift();if(i==="__proto__")return;s[i]?typeof s[i]!="object"&&(s[i]={"":s[i]}):s[i]={},s=s[i]}let u=a[0];typeof s[u]=="object"?s[u][""]=t:s[u]=t}function de(e,r){let t=r?typeof r=="string"?r:".":null,n=Array.isArray(e)?e:V(e,!1),a={};for(let s of n)s instanceof I?j(a,s.key,s.value,t):Array.isArray(s)&&j(a,s[0],s[1],t);return a}F.exports={parse:de,parseLines:V}});var G=h((Ve,D)=>{var{Pair:me,Comment:Ae,EmptyLine:be}=x(),$=(e,r)=>String(e).replace(r!==!1?/[^\t\n\f\r -~\xa1-\xff]/g:/[\0-\b\v\x0e-\x1f]/g,t=>"\\u"+t.charCodeAt(0).toString(16).padStart(4,"0")),z=e=>String(e).replace(/\\/g,"\\\\").replace(/\f/g,"\\f").replace(/\n/g,"\\n").replace(/\r/g,"\\r").replace(/\t/g,"\\t"),J=e=>z(e).replace(/^[#!]|[ =:]/g,"\\$&"),R=e=>z(e).replace(/^ /,"\\ "),Y=(e,r)=>e.replace(/^\s*([#!][ \t\f]*)?/g,r);function w({indent:e,latin1:r,lineWidth:t,newline:n,foldChars:a},s,u){let i=$(s,r),g=$(u,r),o=i+g;if(!t||t<0||o.length<=t)return o;let l=0,p,c=0;s&&i.length<t&&(o=i+n+e+g,l=i.length+n.length,c=l+e.length);for(let A=o[c];A;A=o[++c]){let f=c-l>=t?p||c:void 0;if(!f)switch(A){case"\r":o[c+1]===`
`&&(c+=1);case`
`:f=c+1;break;case"\\":switch(c+=1,o[c]){case"r":o[c+1]==="\\"&&o[c+2]==="n"&&(c+=2);case"n":f=c+1;break;case" ":case"=":case":":a.includes(o[c])&&(p=c+1);break;case"f":a.includes("\f")&&(p=c+1);break;case"t":a.includes("	")&&(p=c+1);break}break;default:a.includes(A)&&(p=c+1)}if(f){let d=f,E=o[d-1];for(;E===`
`||E==="\r";)d-=1,E=o[d-1];let S=o[f],re=S==="	"||S==="\f"||S===" ";o=o.slice(0,d)+n+e+(re?"\\":"")+o.slice(f),l=d+n.length,p=void 0,c=l+e.length-1}}return o}var B=(e,r,t,n="")=>Object.keys(e).reduce((a,s)=>{let u=e[s];if(u&&typeof u=="object")return a.concat(B(u,r,t,n+s+r));{let i=s===t?n.slice(0,-r.length):n+s;return a.push([i,u]),a}},[]);function ke(e,{commentPrefix:r="# ",defaultKey:t="",indent:n="    ",keySep:a=" = ",latin1:s=!0,lineWidth:u=80,newline:i=`
`,pathSep:g=".",foldChars:o="\f	 ."}={}){if(!e)return"";Array.isArray(e)||(e=B(e,g,t));let l={indent:n,latin1:s,lineWidth:u,newline:"\\"+i,foldChars:o},p={indent:r,latin1:s,lineWidth:u,newline:i,foldChars:o};return e.map(c=>{switch(!0){case!c:case c instanceof be:return"";case Array.isArray(c):return w(l,J(c[0])+a,R(c[1]));case c instanceof me:return w(l,J(c.key)+a,R(c.value));case c instanceof Ae:return w(p,"",Y(c.comment,r));default:return w(p,"",Y(String(c),r))}}).join(i)}D.exports={stringify:ke}});var Q=h((Fe,H)=>{var{Node:ve,Pair:xe,Comment:we,EmptyLine:Ee}=x(),{parse:Se,parseLines:Le}=K(),{stringify:Oe}=G();H.exports={Node:ve,Pair:xe,Comment:we,EmptyLine:Ee,parse:Se,parseLines:Le,stringify:Oe}});var X=h(U=>{U.languages=[{name:"Java Properties",type:"data",color:"#2A6277",extensions:[".properties"],tmScope:"source.java-properties",aceMode:"properties",codemirrorMode:"properties",codemirrorMimeType:"text/x-properties",languageId:519377561,since:"0.1.0",parsers:["dot-properties"],vscodeLanguageIds:["properties"]}]});var N=h(($e,W)=>{var{parseLines:qe,stringify:Ie}=Q(),{hardline:Z}=require("prettier").doc.builders,{languages:Me}=X(),Ne={parse:e=>qe(e,!0),astFormat:"dot-properties",hasPragma:e=>/^\s*[#!][ \t\f]*@(pragma|format)\b/.test(e),locStart(e){return Array.isArray(e)&&(e=e[0]),e.range[0]},locEnd(e){return Array.isArray(e)&&(e=e[e.length-1]),e.range[e.range.length-1]}},Pe={print(e,r,t){let n=e.getValue();if(Array.isArray(n))return e.map(u=>this.hasPrettierIgnore(u)?[t(u),Z]:t(u));let a={indent:r.useTabs?"	":" ".repeat(r.tabWidth),keySep:r.keySeparator,latin1:r.escapeNonLatin1,lineWidth:r.printWidth};return[Ie([n],a),Z]},hasPrettierIgnore(e){let r=e.getValue();if(Array.isArray(r))return!1;let t=e.stack[0];if(Array.isArray(t)){let n=t[t.indexOf(r)-1];return n&&n.type==="COMMENT"&&/^\s*[#!][ \t\f]*prettier-ignore/.test(n.comment)}else return!1},insertPragma:e=>`# @format
${e}`},Ce={escapeNonLatin1:{category:"Format",type:"boolean",description:"Escape with \\u all non-Latin-1 characters, to allow safely encoding as ISO-8859-1",default:!1},keySeparator:{category:"Format",type:"choice",description:"The separator to use between a property key and its value",default:" = ",choices:[{value:" "},{value:":"},{value:"="},{value:": "},{value:"= "},{value:" : "},{value:" = "}]}};W.exports={languages:Me,parsers:{"dot-properties":Ne},printers:{"dot-properties":Pe},options:Ce}});var m={};ie(m,{default:()=>ee.default});module.exports=oe(m);v(m,P(N(),1),module.exports);var ee=P(N(),1);
